improved test framework and added test pretty print

diff --git a/tests/Makefile b/tests/Makefile
--- a/tests/Makefile
+++ b/tests/Makefile
@@ -4,6 +4,7 @@ PATCHW_ABS := $(abspath $(PATCHW))
 TEST_DIRS := $(wildcard [0-9]*_*)
 
 YELLOW = \033[0;33m
+RED = \033[0;31m
 RESET = \033[0m
 
 .PHONY: test clean $(TEST_DIRS)
@@ -17,9 +18,16 @@ test:
 	@echo "----------------------------"
 
 $(TEST_DIRS):
-	@./run_test.sh $@ "$(PATCHW_ABS)" "$(PATCHW_ARGS)"
+	@./run_test.sh $@ "$(PATCHW_ABS)" "$(TEST_ARGS)"
 
 clean:
 	@echo "Cleaning test files..."
 	@find . '(' -name "inplace*" -or -name "*.core" ')' -and -type f -delete
 
+pretty-print:
+	@if [ -z "$(TEST)" ]; then \
+		echo -e "$(RED)Error: Please specify a test directory with TEST=directory_name$(RESET)"; \
+		echo "Example: make pretty-print TEST=100_empty-source-addition-patch"; \
+		exit 1; \
+	fi
+	@./pretty-print.sh "$(TEST)"
